services:
   jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/jellyfin
        target: /config/log
      - type: bind
        source: ${APP_DATA_PATH:?}/jellyfin
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /media
    ports:
      - 8096:8096
    networks:
      - streaming
    
    restart: unless-stopped
