services:
 sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      TZ: ${TZ:?}
      PUID: ${PUID:?}
      PGID: ${PGID:?}
    volumes:
      - type: bind
        source: ${APP_LOG_PATH:?}/sonarr
        target: /config/logs
      - type: bind
        source: ${APP_DATA_PATH:?}/sonarr
        target: /config
      - type: bind
        source: ${USER_DATA_PATH:?}
        target: /data
    ports:
      - 8989:8989
    networks:
      - streaming
    depends_on:
      - qbittorrent
    restart: unless-stopped
